import Head from 'next/head';
import Navbar from '../components/Navbar';
import styled from 'styled-components';
import { Text } from '../sharedComponents/index';

const Container = styled.div`
	width: 400px;
	height: 400px;
	background-color: green;
`;

export default function About() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<Container>To jest aboutttt</Container>
			<div>hello</div>
			<Text>hello</Text>
		</>
	);
}
